name: Swift Package SwiftLint

on:
  push:
    paths:
      - '.github/workflows/package-swiftlint.yml'
      - '.swiftlint.yml'
      - '!Examples/**'
      - '**/*.swift'

jobs:
  Package-SwiftLint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --config .swiftlint.yml
